config/routes.rb
QuickBlog::Application.routes.draw do

  get  'about' =>'static_pages#about'
  get  'help' =>'static_pages#help'
  get  'contact' => 'static_pages#contact'

  resources :users, :only => [:new, :create, :show, :edit, :update]
  
  resources :posts, :only => [:index, :new, :create, :show, :edit, :update] do
    resources :comments, :only => [:create]
  end
 

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'posts#index'

  get "*path" => redirect("/")

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Styling based on the <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
    <li> <%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://www.owasp.org/index.php/Main_Page">Security Community</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Internet Security", 'root_path', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>

        <% if current_user %>
            <li><%= link_to 'Edit User', edit_user_path(current_user) %></li>
            <li><%= link_to 'Log out', logout_path, method: "delete" %></li>
        <% else %>
            <li><%= link_to 'Log in', login_path %></li>
            <li><%= link_to 'Sign up', new_user_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= QuickBlog %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>